namespace Loan_CRM.Models
{
    public class ApplicationPersonalVerificationDetails
    {
        public int home_status { get; set; }
        public int DetailId { get; set; }
        public int ApplicationNo { get; set; }
        public int RequestedAmt { get; set; }
        public int RequestedTerms { get; set; }
        public bool Id1_Status { get; set; }
        public bool Id2_Status { get; set; }
        public bool Pi_Status { get; set; }
        public bool Pb_Status { get; set; }
        public string Remarks { get; set; }
        public string AdditionalBirthPlace { get; set; }
        public string AdditionalProvincialAddress { get; set; }
        public string AdditionalLoanPurpose { get; set; }
        public double AdditionalRequestedLoanAmount { get; set; }
        public double AdditionalRequestedTerm { get; set; }
        public double AdditionalEmployedDuration { get; set; }
        public string AdditionalJobPosition { get; set; }
        public string AdditionalJobLevel { get; set; }
        public string AdditionalPayDate { get; set; }
        public bool FamilyPersonalNameStatus { get; set; }
        public bool FamilyPersonalContactStatus { get; set; }
        public bool FamilyRelationWithBorrowerStatus { get; set; }
        public bool FamilyBorrowerKnownDurationStatus { get; set; }
        public bool FamilyAddressVerificationStatus { get; set; }
        public bool FamilyBorrowerWorkingPlaceStatus { get; set; }
        public bool FriendPersonalNameStatus { get; set; }
        public bool FriendPersonalContactStatus { get; set; }
        public bool FriendRelationWithBorrowerStatus { get; set; }
        public bool FriendBorrowerKnownDurationStatus { get; set; }
        public bool FriendAddressVerificationStatus { get; set; }
        public bool FriendBorrowerWorkingPlaceStatus { get; set; }
        public bool CoWorkerPersonalNameStatus { get; set; }
        public bool CoWorkerPersonalContactStatus { get; set; }
        public bool CoWorkerRelationWithBorrowerStatus { get; set; }
        public bool CoWorkerBorrowerKnownDurationStatus { get; set; }
        public bool CoWorkerAddressVerificationStatus { get; set; }
        public bool CoWorkerBorrowerWorkingPlaceStatus { get; set; }
        public bool EmploymentNameOfWorkContactStatus { get; set; }
        public bool EmploymentNoOfWorkConatctStatus { get; set; }
        public bool EmploymentBorrowerWorkingStatus { get; set; }
        public bool EmploymentBorrowerPositionStatus { get; set; }
        public bool EmploymentBorrowerMonthlySalaryStatus { get; set; }
        public bool EmploymentBorrowerAttendanceStatus { get; set; }
        public bool EmploymentBorrowerBankPayrollStatus { get; set; }
        public string FamilyPersonalName { get; set; }
        public string FamilyPersonalContact { get; set; }
        public string FamilyRelationWithBorrower { get; set; }
        public string FamilyBorrowerKnownDuration { get; set; }
        public string FamilyAddressVerification { get; set; }
        public string FamilyBorrowerWorkingPlace { get; set; }
        public string FriendPersonalName { get; set; }
        public string FriendPersonalConatact { get; set; }
        public string FriendRelationWithBorrower { get; set; }
        public string FriendBorrowerKnownDuration { get; set; }
        public string FriendAddressVerification { get; set; }
        public string FriendBorrowerWorkingPlace { get; set; }
        public string CoWorkerPersonalName { get; set; }
        public string CoWorkerPersonalConatact { get; set; }
        public string CoWorkerRelationWithBorrower { get; set; }
        public string CoWorkerBorrowerKnownDuration { get; set; }
        public string CoWorkerAddressVerification { get; set; }
        public string CoWorkerBorrowerWorkingPlace { get; set; }
        public string EmploymentNameOfWorkContact { get; set; }
        public string EmploymentNoOfWorkConatct { get; set; }
        public string EmploymentBorrowerWorking { get; set; }
        public string EmploymentBorrowerPosition { get; set; }
        public string EmploymentBorrowerMonthlySalary { get; set; }
        public string EmploymentBorrowerAttendance { get; set; }
        public string EmploymentBorrowerBankPayroll { get; set; }
        public bool Question1_Status { get; set; }
        public bool Question2_Status { get; set; }
        public bool Question3_Status { get; set; }
        public bool Question4_Status { get; set; }
        public bool Question5_Status { get; set; }
        public bool Question6_Status { get; set; }
        public bool Question7_Status { get; set; }
        public bool Question8_Status { get; set; }
        public bool Question9_Status { get; set; }
        public bool Question10_Status { get; set; }
        public double ApprovedLoanAmount { get; set; }
        public double ApprovedTerm { get; set; }
        public double ApprovedInterestRate { get; set; }
        public string ApprovedMaturityDate { get; set; }
        public double ApprovedTotalDueAmount { get; set; }
        public string NearestLandmark { get; set; }
        public string RentedMortgageOwned { get; set; }
        public string TansferResidence { get; set; }
        public string SpouseName { get; set; }
        public string SpouseOccupation { get; set; }
        public int NumberOfDependent { get; set; }
        public string MotherWork { get; set; }
        public string FatherName { get; set; }
        public string FatherWork { get; set; }
        public string LivingWithMother { get; set; }
        public int SiblingCount { get; set; }
        public string SiblingWorks { get; set; }
        public string Occupation { get; set; }
        public int NetIncome { get; set; }
        public string PendingResignation { get; set; }
        public string OtherSourceOfIncome { get; set; }
        public string KnowAboutCashmart { get; set; }
        public string PendingLoanFronOtherland { get; set; }
        public string BankLoanOrCreditCard { get; set; }
        public string PermanentAddress { get; set; }
        public int BankId { get; set; }
        public string FamilyName1 { get; set; }
        public string FamilyAddress1 { get; set; }
        public string FamilyContact1 { get; set; }
        public string FamilyRelation1 { get; set; }
        public string FamilyName2 { get; set; }
        public string FamilyAddress2 { get; set; }
        public string FamilyContact2 { get; set; }
        public string FamilyRelation2 { get; set; }
        public string OptionalName { get; set; }
        public string OPptionalAddress { get; set; }
        public string OptionalContact { get; set; }
        public string OptionalRelation { get; set; }
        public string NoonTime { get; set; }
        public string MorningTime { get; set; }
    }
}