using System;

namespace Loan_CRM.Models
{
    public class ApplicationDataVerificationDetais
    {
        public int verification_id { get; set; }
        public int application_no { get; set; }
        public bool personal_name_id1_status { get; set; }
        public bool personal_name_id2_status { get; set; }
        public bool personal_name_pi_status { get; set; }
        public bool personal_name_pb_status { get; set; }
        public bool personal_email_id1_status { get; set; }
        public bool personal_email_id2_status { get; set; }
        public bool personal_email_pi_status { get; set; }
        public bool personal_email_pb_status { get; set; }
        public bool personal_contact_no_id1_status { get; set; }
        public bool personal_contact_no_id2_status { get; set; }
        public bool personal_contact_no_pi_status { get; set; }
        public bool personal_contact_no_pb_status { get; set; }
        public bool personal_perma_address_id1_status { get; set; }
        public bool personal_perma_address_id2_status { get; set; }
        public bool personal_perma_address_pi_status { get; set; }
        public bool personal_perma_address_pb_status { get; set; }
        public bool personal_house_ph_id1_status { get; set; }
        public bool personal_house_ph_id2_status { get; set; }
        public bool personal_house_ph_pi_status { get; set; }
        public bool personal_house_ph_pb_status { get; set; }
        public bool personal_birth_place_id1_status { get; set; }
        public bool personal_birth_place_id2_status { get; set; }
        public bool personal_birth_place_pi_status { get; set; }
        public bool personal_birth_place_pb_status { get; set; }
        public bool personal_birth_date_id1_status { get; set; }
        public bool personal_birth_date_id2_status { get; set; }
        public bool personal_birth_date_pi_status { get; set; }
        public bool personal_birth_date_pb_status { get; set; }
        public bool personal_civil_id1_status { get; set; }
        public bool personal_civil_id2_status { get; set; }
        public bool personal_civil_pi_status { get; set; }
        public bool personal_civil_pb_status { get; set; }
        public bool personal_mother_maiden_name_id1_status { get; set; }
        public bool personal_mother_maiden_name_id2_status { get; set; }
        public bool personal_mother_maiden_name_pi_status { get; set; }
        public bool personal_mother_maiden_name_pb_status { get; set; }
        public bool personal_mother_perma_add_id1_status { get; set; }
        public bool personal_mother_perma_add_id2_status { get; set; }
        public bool personal_mother_perma_add_pi_status { get; set; }
        public bool personal_mother_perma_add_pb_status { get; set; }
        public bool personal_company_name_id1_status { get; set; }
        public bool personal_company_name_id2_status { get; set; }
        public bool personal_company_name_pi_status { get; set; }
        public bool personal_company_name_pb_status { get; set; }
        public bool personal_company_address_id1_status { get; set; }
        public bool personal_company_address_id2_status { get; set; }
        public bool personal_company_address_pi_status { get; set; }
        public bool personal_company_address_pb_status { get; set; }
        public bool personal_job_title_id1_status { get; set; }
        public bool personal_job_title_id2_status { get; set; }
        public bool personal_job_title_pi_status { get; set; }
        public bool personal_job_title_pb_status { get; set; }
        public bool personal_monthly_income_id1_status { get; set; }
        public bool personal_monthly_income_id2_status { get; set; }
        public bool personal_monthly_income_pi_status { get; set; }
        public bool personal_monthly_income_pb_status { get; set; }
        public bool personal_reference_name_id1_status { get; set; }
        public bool personal_reference_name_id2_status { get; set; }
        public bool personal_reference_name_pi_status { get; set; }
        public bool personal_reference_name_pb_status { get; set; }
        public bool personal_reference_contact_id1_status { get; set; }
        public bool personal_reference_contact_id2_status { get; set; }
        public bool personal_reference_contact_pi_status { get; set; }
        public bool personal_reference_contact_pb_status { get; set; }
        public bool personal_bank_name_id1_status { get; set; }
        public bool personal_bank_name_id2_status { get; set; }
        public bool personal_bank_name_pi_status { get; set; }
        public bool personal_bank_name_pb_status { get; set; }
        public bool personal_bank_ac_no_id1_status { get; set; }
        public bool personal_bank_ac_no_id2_status { get; set; }
        public bool personal_bank_ac_no_pi_status { get; set; }
        public bool personal_bank_ac_no_pb_status { get; set; }
        public bool personal_req_loan_amt_id1_status { get; set; }
        public bool personal_req_loan_amt_id2_status { get; set; }
        public bool personal_req_loan_amt_pi_status { get; set; }
        public bool personal_req_loan_amt_pb_status { get; set; }
        public bool personal_req_loan_term_id1_status { get; set; }
        public bool personal_req_loan_term_id2_status { get; set; }
        public bool personal_req_loan_term_pi_status { get; set; }
        public bool personal_req_loan_term_pb_status { get; set; }
        public String personal_name_remark { get; set; }
        public String personal_email_remark { get; set; }
        public String personal_contact_no_remark { get; set; }
        public String personal_perma_address_remark { get; set; }
        public String personal_house_ph_remark { get; set; }
        public String personal_birth_place_remark { get; set; }
        public String personal_birth_date_remark { get; set; }
        public String personal_civil_remark { get; set; }
        public String personal_mother_maiden_name_remark { get; set; }
        public String personal_mother_perma_add_remark { get; set; }
        public String personal_company_name_remark { get; set; }
        public String personal_company_address_remark { get; set; }
        public String personal_job_title_remark { get; set; }
        public String personal_monthly_income_remark { get; set; }
        public String personal_reference_name_remark { get; set; }
        public String personal_reference_contact_remark { get; set; }
        public String personal_bank_name_remark { get; set; }
        public String personal_bank_ac_no_remark { get; set; }
        public String personal_req_loan_amt_remark { get; set; }
        public String personal_req_loan_term_remark { get; set; }

    }
}